# Generated by Django 2.2.6 on 2019-10-29 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CachedZone',
            fields=[
                ('key', models.CharField(max_length=250, primary_key=True, serialize=False, unique=True)),
                ('tag', models.CharField(max_length=250)),
                ('value', models.TextField(max_length=250)),
                ('updated', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('nick', models.CharField(max_length=250, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('name', models.CharField(max_length=250, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OperatingSystem',
            fields=[
                ('name', models.CharField(max_length=250, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('name', models.CharField(max_length=250, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('name', models.CharField(max_length=250, primary_key=True, serialize=False, unique=True)),
                ('ttl', models.IntegerField(blank=True, null=True, verbose_name='TTL')),
                ('templates', models.ManyToManyField(blank=True, to='netmgt.Template')),
            ],
        ),
        migrations.CreateModel(
            name='ZoneRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250)),
                ('ttl', models.IntegerField(blank=True, null=True, verbose_name='TTL')),
                ('type', models.CharField(choices=[('A', 'A'), ('AAAA', 'AAAA'), ('CAA', 'CAA'), ('CERT', 'CERT'), ('CNAME', 'CNAME'), ('DNSKEY', 'DNSKEY'), ('DS', 'DS'), ('DNSKEY', 'DNSKEY'), ('KEY', 'KEY'), ('LOC', 'LOC'), ('MX', 'MX'), ('NAPTR', 'NAPTR'), ('NS', 'NS'), ('NSEC', 'NSEC'), ('PTR', 'PTR'), ('RRSIG', 'RRSIG'), ('SPF', 'SPF'), ('SRV', 'SRV'), ('TXT', 'TXT')], max_length=8)),
                ('value', models.CharField(max_length=250)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='netmgt.Zone')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TemplateRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250)),
                ('ttl', models.IntegerField(blank=True, null=True, verbose_name='TTL')),
                ('type', models.CharField(choices=[('A', 'A'), ('AAAA', 'AAAA'), ('CAA', 'CAA'), ('CERT', 'CERT'), ('CNAME', 'CNAME'), ('DNSKEY', 'DNSKEY'), ('DS', 'DS'), ('DNSKEY', 'DNSKEY'), ('KEY', 'KEY'), ('LOC', 'LOC'), ('MX', 'MX'), ('NAPTR', 'NAPTR'), ('NS', 'NS'), ('NSEC', 'NSEC'), ('PTR', 'PTR'), ('RRSIG', 'RRSIG'), ('SPF', 'SPF'), ('SRV', 'SRV'), ('TXT', 'TXT')], max_length=8)),
                ('value', models.CharField(max_length=250)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='netmgt.Template')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('info', models.CharField(blank=True, max_length=250)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='netmgt.Contact')),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='netmgt.OperatingSystem', verbose_name='Operating System')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='netmgt.DeviceType')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('prefix_len', models.IntegerField(verbose_name='Prefix Length')),
                ('name', models.CharField(max_length=250)),
                ('reverse_zone', models.CharField(max_length=250)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='netmgt.Device')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='netmgt.Zone')),
            ],
        ),
    ]
