# Generated by Django 5.1.2 on 2025-09-04 20:30

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		("netmgt", "0001_initial"),
	]

	operations = [
		migrations.AddField(
			model_name="zone",
			name="acme_admin_token",
			field=models.CharField(blank=True, max_length=250),
		),
		migrations.AddField(
			model_name="zone",
			name="acme_challange",
			field=models.CharField(blank=True, max_length=250),
		),
	]
