# Generated by Django 5.1.2 on 2026-09-20 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		("netmgt", "0003_alter_templaterecord_value_alter_zonerecord_value"),
	]

	operations = [
		migrations.AlterField(
			model_name="templaterecord",
			name="value",
			field=models.TextField(),
		),
		migrations.AlterField(
			model_name="zonerecord",
			name="value",
			field=models.TextField(),
		),
	]
