# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-09 10:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netmgt', '0003_cachedzone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='prefix_len',
            field=models.IntegerField(verbose_name='Prefix Length'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='device',
            name='os',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netmgt.OperatingSystem', verbose_name='Operating System'),
        ),
        migrations.AlterField(
            model_name='templaterecord',
            name='ttl',
            field=models.IntegerField(blank=True, null=True, verbose_name='TTL'),
        ),
        migrations.AlterField(
            model_name='templaterecord',
            name='type',
            field=models.CharField(choices=[('A', 'A'), ('AAAA', 'AAAA'), ('CERT', 'CERT'), ('CNAME', 'CNAME'), ('DNSKEY', 'DNSKEY'), ('DS', 'DS'), ('DNSKEY', 'DNSKEY'), ('KEY', 'KEY'), ('LOC', 'LOC'), ('MX', 'MX'), ('NAPTR', 'NAPTR'), ('NS', 'NS'), ('NSEC', 'NSEC'), ('PTR', 'PTR'), ('RRSIG', 'RRSIG'), ('SPF', 'SPF'), ('SRV', 'SRV'), ('TXT', 'TXT')], max_length=8),
        ),
        migrations.AlterField(
            model_name='zone',
            name='templates',
            field=models.ManyToManyField(blank=True, to='netmgt.Template'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='ttl',
            field=models.IntegerField(blank=True, null=True, verbose_name='TTL'),
        ),
        migrations.AlterField(
            model_name='zonerecord',
            name='ttl',
            field=models.IntegerField(blank=True, null=True, verbose_name='TTL'),
        ),
        migrations.AlterField(
            model_name='zonerecord',
            name='type',
            field=models.CharField(choices=[('A', 'A'), ('AAAA', 'AAAA'), ('CERT', 'CERT'), ('CNAME', 'CNAME'), ('DNSKEY', 'DNSKEY'), ('DS', 'DS'), ('DNSKEY', 'DNSKEY'), ('KEY', 'KEY'), ('LOC', 'LOC'), ('MX', 'MX'), ('NAPTR', 'NAPTR'), ('NS', 'NS'), ('NSEC', 'NSEC'), ('PTR', 'PTR'), ('RRSIG', 'RRSIG'), ('SPF', 'SPF'), ('SRV', 'SRV'), ('TXT', 'TXT')], max_length=8),
        ),
    ]
