# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-09 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netmgt', '0004_auto_20170509_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templaterecord',
            name='type',
            field=models.CharField(choices=[('A', 'A'), ('AAAA', 'AAAA'), ('CAA', 'CAA'), ('CERT', 'CERT'), ('CNAME', 'CNAME'), ('DNSKEY', 'DNSKEY'), ('DS', 'DS'), ('DNSKEY', 'DNSKEY'), ('KEY', 'KEY'), ('LOC', 'LOC'), ('MX', 'MX'), ('NAPTR', 'NAPTR'), ('NS', 'NS'), ('NSEC', 'NSEC'), ('PTR', 'PTR'), ('RRSIG', 'RRSIG'), ('SPF', 'SPF'), ('SRV', 'SRV'), ('TXT', 'TXT')], max_length=8),
        ),
        migrations.AlterField(
            model_name='zonerecord',
            name='type',
            field=models.CharField(choices=[('A', 'A'), ('AAAA', 'AAAA'), ('CAA', 'CAA'), ('CERT', 'CERT'), ('CNAME', 'CNAME'), ('DNSKEY', 'DNSKEY'), ('DS', 'DS'), ('DNSKEY', 'DNSKEY'), ('KEY', 'KEY'), ('LOC', 'LOC'), ('MX', 'MX'), ('NAPTR', 'NAPTR'), ('NS', 'NS'), ('NSEC', 'NSEC'), ('PTR', 'PTR'), ('RRSIG', 'RRSIG'), ('SPF', 'SPF'), ('SRV', 'SRV'), ('TXT', 'TXT')], max_length=8),
        ),
    ]
